server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://193.218.142.195:5432/blps_lab1
    username: postgres
    password: intmain321890
#   url: jdbc:postgresql://pg:5432/studs
#   username: s309629
#   password: aMLiRX06Jmx2udY4

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: 193.218.142.195:9093
    group-id: user-check-group